create table if not exists public.blessings (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  author_id text,
  created_at timestamptz not null default now()
);

create index if not exists blessings_created_at_idx
  on public.blessings (created_at desc);

insert into public.blessings (name, message, author_id)
select seed.name, seed.message, 'seed'
from (
  values
    ('Family Friend', 'Wishing you both a lifetime of laughter, love, and beautiful memories.'),
    ('Well Wisher', 'May your marriage be filled with joy, blessings, and endless togetherness.')
) as seed(name, message)
where not exists (select 1 from public.blessings);
